#+TITLE: BirthDay Adventure
#+AUTHOR: Kartashov_Home
*  ваншот, коротенький и быстрый:
* Вступление:  
  Мы остановились у врат в заброшенный храм. Остатки былого величия смотрят из разбитых статуй и покореженных зданий. Ржавые доспехи, чудом сохранившиеся, торчат то здесь, то там
  Врата повело, и одна створка вывалилась наружу, открывая путь в зияющую пустоту. Оттуда слышны какие-то хрипы и охи. Скрежет раздается эхом. Воздух будто звенит,
  заставляя по коже пробегать мурашки, а душу леденеть от ужаса. 
* АКТ 1. Нисхождение.
  Войдя в храм, путники сразу ощутили что это место древнее, зловещее, но когда-то здесь царил свет и уют. Примерно такие же ощущения могут посетить вас, когда вы попадаете в старый, заброшенный дом своей бабушки и 
  натыкаетесь на противоречия воспоминаний и действительности. Герои попадают в небольшую залу, тамбур, где находятся пункт охраны, зал ожидания и несколько входов в храм. Пункт охраны прекрасно сохранился, на стойках 
  остались некоторые образцы оружия и доспехов. Но останков охранников, прекрасных эльфийских стрелков, нет. 
*** Находки:
- Карта подземелья 
- Инструкции охране по ловушкам и секретам
- Амулет охранный (1)
- Эльфийский кинжал (равносилен стандартной рапире)

*** Зал:
  В зале ожидания расставлены стулья, во многом уже сломанные. Зал достаточно большой, на стенах развешаны гобелены со сценами боевых столкновений эльфов и различными историческими событиями. По центру стоит монумент с 
   тремя эльфами - по центру сидит темный эльф(дроу) с двумя кинжалами, рядом с ним, полуприсев с луком наизготовку лесной эльф, а справа в полный рост, держа в руке звезду, высший эльф. Внизу монумента надпись.Её можно прочесть
   только при удачной проверке внимательности (сл. 18). 
*** Надпись
"В глазах сияя свет, в душе его уж нет, И сочетая в сердце ярость, там путь найдет лишь храбрость".
*** Пасхалки
В зале также можно найти несколько пасхалок на гобеленах, например темного эльфа с пантерой или гнома среди льдов. Помимо этого, за одним из гобеленов есть тайник (сл 16)
*** Тайник:
- Магический фонарь
- Эльфийская еда, которая не портится
- Ноты древних баллад
- Эльфийская печать
** Развилка 
   Закончив с этим залом, путники оказываются перед тремя входами в подгорный храм. Первый ведет в покои эльфийского короля. Второй в сокровищницу и резиденцию. Третий собственно в храм и реликварий.
   В зависимости от выбора пути, различается и дальнейшее прохождение.
* АКТ 2. Путь.
** Вход первый:
Вход к покоям короля заперт, поэтому придется взламывать замки (сл. 16)
После успешного взлома, перед героями оказывается узкий коридор, где пройти может один человек. Необходимо определить порядок и инициативу. 
------ /В этом коридоре на вас нападут несколько зомби, самых обычных/
**** Зомби:
Средний, нежить, нейтрально-злой
Класс Доспеха 8
Хиты 22 (3к8 + 9)
Скорость 20 футов
СИЛ 13 (+1)
ЛОВ 6 (-2)
ТЕЛ 16 (+3)
ИНТ 3 (-4)
МДР 6 (-2)
ХАР 5 (-3)
Иммунитет к урону яд
Иммунитет к состоянию отравление
Спасброски МДР +0
Чувства тёмное зрение 60 футов, пассивное Восприятие 8
Опасность 1/4 - 50 опыта
Источник: «Monster manual»
Языки. Понимает языки, которые знал при жизни, но не может говорить.
Стойкость нежити. Если зомби получает урон, уменьшающий хиты до 0, он совершает спасбросок Телосложения со Сл 5 + полученный урон, если только это не был урон излучением или урон от критического попадания.
 При успехе хиты зомби опускаются всего лишь до 1.
ДЕЙСТВИЯ
Размашистый удар. Рукопашная атака оружием: +3 к попаданию, досягаемость 5 футов, одна цель. Попадание: Дробящий урон 4 (1к6 + 1).
*** Вход в покои:
Двери будут выломаны, внутри царит беспорядок и веет холодом. Также вы замечаете (сл 12 внимательность) что там есть зеленые отсветы на стенах. 
Внутри вас будут ждать три зомби и одно умертвие
**** Умертвие:
Средний, нежить, нейтрально-злой
Класс Доспеха 14 (проклепанная кожа)
Хиты 45 (6к8 + 18)
Скорость 30 футов
СИЛ 15 (+2)
ЛОВ 14 (+2)
ТЕЛ 16 (+3)
ИНТ 10 (0)
МДР 13 (+1)
ХАР 15 (+2)
Сопротивление урону колющий, рубящий, дробящий, некротическая энергия
Иммунитет к урону яд
Иммунитет к состоянию отравление, истощение
Навыки Скрытность +4, Восприятие +3
Чувства тёмное зрение 60 футов, пассивное Восприятие 13
Опасность 3 - 700 опыта
Источник: «Monster manual»
Сопротивление к немагическому и немагическому непосеребренному дробящему, колющему и рубящему урону.
Языки - все, известные при жизни.
Чувствительность к солнечному свету. Находясь на солнечном свету, умертвие совершает с помехой броски атаки, а также проверки Мудрости (Восприятие), полагающиеся на зрение.
ДЕЙСТВИЯ
Мультиатака. Умертвие совершает две атаки длинным мечом или длинным луком. Оно может использовать Вытягивание жизни вместо одной атаки длинным мечом.
Вытягивание жизни. Рукопашная атака оружием: +4 к попаданию, досягаемость 5 футов, одно существо. Попадание: Урон некротической энергией 5 (1к6 + 2). Цель должна преуспеть в спасброске
 Телосложения со Сл 13, иначе максимум её хитов уменьшится на количество, равное полученному урону. Это уменьшение длится до тех пор, пока цель не окончит продолжительный отдых. 
Цель умирает, если этот эффект уменьшает максимум хитов до 0.
Гуманоид, убитый этой атакой, восстает через 24 часа в качестве зомби под контролем умертвия, если этого гуманоида не воскресят, или его тело не уничтожат.
 У умертвия может быть не более двенадцати зомби под контролем одновременно.
Длинный меч. Рукопашная атака оружием: +4 к попаданию, досягаемость 5 футов, одна цель. Попадание: Рубящий урон 6 (1к8 + 2), или рубящий урон 7 (1к10 + 2), если используется двумя руками.
Длинный лук. Дальнобойная атака оружием: +4 к попаданию, дистанция 150/600 футов, одна цель. Попадание: Колющий урон 6 (1к8 + 2).
ОПИСАНИЕ
Умертвие это смертный, ведомый темными желаниями и большим тщеславием, впоследствии ставший злой нежитью. Когда смерть усмиряет сердце подобного существа и жизнь покидает его, 
дух сего создания взывает к демоническому повелителю Оркусу или другому отвратительному богу подземного мира для отсрочки: он просит возродиться в качестве нежити в обмен на вечную войну с живыми. 
Если темная сила отвечает на зов, сей дух становится нежитью, способной осуществлять свои собственные злые планы.
Умертвия обладают памятью и повадками своей былой жизни. Они будут прислушиваться к зову той темной сущности, что превратила их в нежить, но сохраняют при этом свою независимость. 
Не знающее усталости умертвие может преследовать свои цели безжалостно, и ни на что не отвлекаясь.
Пожиратели жизни. Не живое и при этом не мертвое, умертвие существует в промежуточном состоянии между двух миров. Жизнерадостность, которой оно обладало при жизни, исчезает, и на её место приходит
 жажда поглощать всякую жизненную искру, которую оно найдет на своем пути. Когда умертвие нападает, мрачные глаза, сего ожившего существа тлеют словно раскаленные добела горячие угольки, 
и холодное прикосновение умертвия может истощить жизненную силу сквозь плоть, одежду и доспехи.
Могильная тень. Умертвия избегают дневного мира и солнечного света, который они ненавидят. Они отступают в могильные курганы, склепы и усыпальницы, в которых они обитают. 
Их логова расположены в беззвучных пустынных местах, в окружении почерневших мертвых растений, а звери и птицы сторонятся их.
Гуманоиды, убитые умертвием, могут подняться подконтрольными им зомби. Движимые жаждой живых душ и тягой к силам, пробудивших их в посмертии, 
некоторые умертвия служат ударными войсками злых лидеров, таких как призраки. Будучи солдатами, они способны планировать, но делают это редко, полагаясь на жажду разрушения при подавлении любых противников.
Натура нежити. Умертвию не нужен воздух, еда, питье и сон.
*** Находки и тайники:
Покои богато украшены и внутри несколько сундуков с сокровищами, библиотека с книгами и много оружия.
- Золотые украшения (5)
- Книга заклинаний 5 уровня
- Книга историй
- Книга света
- Летопись
- Эльфийский клинок
- Копье
- Шлем
- Комплект доспехов короля(изгнивший)

