#+HEAD: hidestars
#+AUTHOR: Kartashov_Home
#+TITLE: RULES and BASIC
* Краткие базовые механики: 
** Для начала вступление - мир такой какой пожелаете.
** Придумайте себе персонажа, а именно:
*** Придумайте ему имя, фамилию.
*** Придумайте ему предысторию. 
*** Выберите его расу или вид.
*** Выберите его класс.
*** Определите значения и характеристики.
*** Опишите внешность героя, его отличительные черты.
*** Определите начальное снаряжение персонажа.
*** Придумайте завязку истории.
* Броски кубика:
** Кубиков всего 6, но может быть и больше. Самый важный 20ти гранный. 
** Бросок кубика сопровождается добавлением модификатора из листа персонажа.
** Также есть так называемые спас броски. При попадании противника можете совершить спасбросок.
* Атака:
** Подойдите к противнику для ближнего боя или выберите дальний бой.
** Выберите оружие, которым будете атаковать.
** Бросьте кубик и прибавьте к нему модификатор атаки вашего оружия.
** Проверьте класс доспеха противника.
** Если нанесенный вами урон превышает класс доспеха противника, то ему наносится урон. У ГМ есть возможность совершить спасбросок.
** В зависимости от класса и расы персонажа, он может совершить дополнительное действие или дать бонусы(баффы) команде.
* Основные формулы:
** Модификатор характеристики: (Характеристика - 10) / 2. Округление в меньшую сторону.
** Атака ближнего боя: 1к20 + Мастерство + СИЛ (ЛОВ для изящного оружия)
** Урон ближнего боя: Кость оружия + СИЛ (ЛОВ для изящного оружия)
** Атака дальнего боя: 1к20 + Мастерство + ЛОВ (СИЛ для метательного оружия)
** Урон дальнего боя: Кость оружия + ЛОВ (СИЛ для метательного оружия)
** Атака заклинанием: 1к20 + Мастерство + Модификатор характеристики сотворения заклинания
** Урон заклинания: индивидуален для каждого заклинания
** Сложность спасброска от заклинания: 8 + Модификатор характеристики + Мастерство
** Спасбросок: 1к20 + Модификатор характеристики
** Порядок ходов в бою: 1к20 + Инициатива (ЛОВ)
** Пассивная внимательность: 10 + МДР (Восприятие)
** Стабилизация умирающего: 1к20 + МДР (Медицина) - Сл:10
** Применение инструментов: 1к20 + Модификатор характеристики (скажет ДМ) + Мастерство
* Ход игры:
** Мастер игры рассказывает историю вашего приключения.
** Он создает ситуации, на которые игроки будут реагировать.
** Используя воображение и броски кубика, игроки и мастер вместе создают полотно истории.
** По ходу повествования игроки могут без очереди высказываться, главное по одному.
** В бою же важен порядок ходов и инициатива.
* Таблица характеристик:
** Значение	Модификатор
*** 1	                  −5
*** 2–3	−4
*** 4–5	−3
*** 6–7	−2
*** 8–9	−1
*** 10–11	+0
*** 12-13	+1
*** 14–15	+2
*** 16–17	+3
*** 18–19	+4
*** 20–21	+5
*** 22–23	+6
*** 24–25	+7
*** 26–27	+8
*** 28–29	+9
*** 30	+10
* Сложность проверок:
*** Сложность Задачи	           УС
**** Очень легко	                  5
**** Легко	                                10
****  Средний	                                15
**** Трудно	                                20
**** Очень трудно	                25
**** Почти невозможно	30
* Использование характеристик:
** Сила
*** Сила измеряет физическую силу, спортивную подготовку и предел, в котором вы можете применить грубую физическую силу.
*** Проверки Силы
**** Проверка силы может моделировать любую попытку поднять, толкнуть, потянуть или сломать что-то, заставить ваше тело пройти через пространство или иным образом применить грубую силу к ситуации. 
**** Навык Атлетика отражает способности к некоторым проверкам Силы.
***  Атлетика. Проверка Вашей силы (Атлетика) охватывает сложные ситуации, с которыми вы сталкиваетесь во время восхождения, прыжков или плавания. В качестве примеров можно привести следующие активности::
**** Вы пытаетесь взобраться на отвесный или скользкий Утес, избегаете опасностей, взбираясь на стену, или цепляетесь за поверхность, когда что-то пытается сбить вас.
****  Вы пытаетесь прыгнуть на необычно большое расстояние или совершить трюк в середине прыжка.
**** Вы пытаетесь плыть или оставаться на плаву в коварных течениях, штормовых волнах или среди густых зарослей водорослей. Или другое существо пытается подтолкнуть или затаить вас под воду или иным образом помешать вашему плаванию.
*** Другие проверки силы. Мастер также может потребовать проверки силы, когда вы пытаетесь выполнить следующие задачи:
**** Силой открыть застрявшую, запертую или заложенную на засов дверь
**** Освободиться от пут
**** Протиснутся через туннель, который слишком мал
**** Попытка удержаться за фургон, не отцепившись от него во время движения
**** Опрокинуть статую
****  Держите валун от скатывания
*** Броски атаки и урона
**** Вы добавляете свой модификатор силы к броску атаки и броску урона, когда атакуете оружием ближнего боя, таким как булава, боевой топор или копье. 
**** Вы используете оружие ближнего боя, чтобы совершать атаки в ближнем бою, и некоторые из них можно метать совершая дальнобойную атаку.
***  Подъём и перенос
**** Значение Силы определяет вес, который вы можете переносить. Следующие термины определяют то, что вы можете поднять или нести.
*****  Грузоподъемность. Ваша грузоподъёмность это ваше значение Силы, умноженное на 15. Такой вес (в фунтах) вы можете носить, и это достаточно много, так что большинству персонажей не нужно об этом заботиться.
*****   Толкание, волочение и подъём. . Вы можете толкать, тянуть и отрывать от земли вес в фунтах, вдвое превышающий вашу грузоподъёмность (или значение Силы, умноженное на 30)
***** Если вы толкаете или тянете вес, превышающий грузоподъёмность, ваша скорость падает до 5 футов.
*****   Размер и сила. Более крупные существа могут нести больший вес, в то время как Крохотные существа могут нести меньше. 
***** Для каждой категории размера выше среднего удвоите грузоподъемность существа и вес, который оно может толкать, тянуть или поднимать. 
***** Для существа Крохотного размера уменьшите эти значения вдвое.
****   Вариация: нагрузка
*****  Правила по грузоподъёмности и перемещению предметов упрощены намеренно. 
***** Вот вариант, если вы ищете более подробные правила для определения того, как персонаж ограничен ве.сом снаряжения Когда вы используете такой вариант, игнорировать столбец Сила в таблице Доспехи.
*****   Если вы несете вес, превышающий в 5 раз значение Вашей Силы, вы нагружены, что означает, что ваша скорость падает на 10 футов.
*****   Если вы несете вес, превышающий в 10 раз значение Вашей Силы, вплоть до максимальной грузоподъемности, вы вместо этого сильно нагружены, 
***** что означает, что ваша скорость падает на 20 футов, и у вас есть помеха в проверках характеристик, бросках атаки и спасбросках, использующие Силу, Ловкость или Телосложение.
** Ловкость
*** 
