#+HEAD: В поисках дракона
#+TITLE: Книга о приключении
#+DATE: <2021-12-10>
* Предисловие
** Пояснения
   Эта книга была создана как новеллизация или дополнение художественными и авторскими приемами нашей с друзьями компании из "Подземелий и Драконов".
   Почему это интересно? Потому, что играли мы в новом для себя формате игры сообщениями. Мастер (Это был я) описывал историю и обстановку сначала в инстаграмме,
   а потом и в телеграмме. Игроки же отвечали на это. Такой формат был выбран в силу ковидных ограничений, а также потому, что банально не можем собраться
   в одном месте на несколько часов без отрыва от игры. Изначально играли вообще без бросков и листов, оставив лишь описательную часть. Но когда дело дошло до
   сражений, то и кубики, и характеристики были заведены. Надеюсь, вам будет интересно почитать прохождение моего авторского приключения. Кстати, именно поэтому
   можете наблюдать некоторые нестыковки или хаотичность повествования. Спасибо! 
** Благодарности
   Я сердечно благодарю людей, которые не только поверили в мою способность рассказывать истории, но и продолжают поддерживать меня на этом пути.
** Для кого эта книга
   Эта книга для нас, игроков в "D&D", а также для всех, кого заинтересовало мое творчество. Книга абсолютно бесплатна, обратите на это внимание.
* Введение
  В маленьком городке Хорн, который издавна отличался от прочих горных городов своим выгодным расположением и объединял в себе множество культур и языков.
  Он стоял на пороге гор, являясь по сути последним приютом перед долгим маршрутом через перевалы и массивы хребтов, покрытых снежными шапками. Где-то там,
  высоко, было еще множество храмов и городов, которые могли состоять как из десятков зданий, так и из двух дворов. Древние храмы с монахами, подземные святилища
  и много таинств скрывались там.
  Город привлекал к себе много внимания, и зачастую здесь можно было встретить толпы приключенцев, солдат или просто зевак, решивших путешествовать через горы. Когда с гор
  начинал спускаться дикий, пронзительный ветер и в каменных, крепко сложенных домах зажигались фонари, а стража, зябко поежившись, куталась в тулупы, вовсю начинали работать таверны.
  Они собирали в себя весь цвет города, начиная от приезжих головорезов и заканчивая аристократами, которых впрочем было немного. А выходило из таверн в приличном состоянии и того меньше.
  Наша история начинается в таверне "Скрещенные Топоры", что стоит почти в самом центре, на пересечении улицы Керамщиков и Оружейного переулка. Массивное здание с двумя этажами являло
  собой чуть ли не самую яркую достопримечательность данных мест. Огромные дубовые ворота встречали путника, а за ними массивный зал с круглыми столиками и резными стульями, барной стойкой
  с огромным, но всегда вежливым трактирщиком-полуорком. В камине радостно потрескивали поленья, облизывая языками пламени каменные своды. В дальнем углу компания сдвинула столы и изрядно набравшись,
  пела песни. На небольшом помосте в самом центре таверны тренькал на лютне бард-полуэльф. Обстановка не располагала к каким-то потрясениям. Отсюда и начинается наш рассказ.
* Глава 1.
  Дверь распахнулась, будто пушинка. В таверну вошел человек в доспехах, покрытых инеем, все же на улице холодно. Он снял шлем и внимательно обвел взглядом зал, а затем, тяжело ступая, направился
  прямиком к барной стойке. Посетители таверны не сводили взгляда с незванного гостя, даже музыка прекратила играть.
  -"Эй, хозяин! Я - Юстас Болдер, из Ордена Пылающего Сердца. Кружку эля, будь добр. И расскажи, есть ли какое-нибудь задание для меня?" - Он достал из кошеля монетку и положил на стойку перед собой.
  Трактирщик поставил перед гостем оловяную кружку и облокотившись на стойку сказал:
  -"Таких как ты, здесь не любят. Вы как появитесь, так начинаете всем свои правила диктовать. Мы подчиняться и следовать вашему кодексу не обязаны".
  В ответ рыцарь поднял руку в примиряющем жесте:
  -"Спокойно, я просто зашел выпить да найти себе занятие, чтоб подзаработать. Не стоит судить обо всех нас по слухам и домыслам".
  Полуорк нахмурился, но кивнул паладину. Он достал небольшой футляр из-под стойки и положил перед рыцарем.
  -"Вот небольшое дельце. А здесь ты можешь найти желающих помочь".
  Паладин в ответ ухмыльнулся:
  -"Да я и сам справлюсь. Мне помощь не нужна".
  Тут же раздался голос полуэльфа над ухом рыцаря:
  -"Приятель, я готов отправиться с тобой, дабы впоследствии сложить баллады о наших приключениях за весьма небольшой процент от добычи. К тому же, местные
  не ценят искусство, им лишь бы пожрать да поспать. Помоги мне добраться до городка на вершине горы, а я помогу тебе. Идет?"
  Паладин пожал протянутую руку и улыбнулся новому другу:
  -" Я - Юстас Болде..."
  -"Да я слышал, слышал" - Бард перебил рыцаря и продолжил, - "Плутик Орбо, самый известный и легендарный поэт в этой части материка к вашим услугам!". Плутик манерно
  преклонил голову, когда услышал из дальнего угла презрительный смех и голос:
  -"Мечтай, полуэльф. Тебя ж никто всерьез не воспринимает. Да и не знает никто" - Тифлинг встала из-за своего столика, хищно ухмыляясь. Её длинные седые локоны будто расплескались по
  изящной меховой накидке. Бард схватился за кинжал, не сводя глаз с колдуньи. Колдунья же открыла ладонь, в которой уже разгоралось пламя. Напряжение нарастало, и вдруг раздался звук,
  будто сковородкой ударили по дереву. Бард осел на пол, обхватив стул.
  -"Кажется, он слишком много болтает" - Юстас потирал руку в перчатке.   
* Глава 2.
