#+TITLE: Podcast's plane
#+DATE: <2022-18-11>

* Выпуск 1.
** О чем?
Хотел бы записать подкаст в начале о создании персонажа.
** Примерная длительность
6-7 минут
** Название
Драконы не дремлют.
** Коронная фраза в конце
- Что вы будете делать?
- Киньте на инициативу!
- Сделайте бросок с преимуществом!
- А теперь вперед, к приключениям!
** Текст подкаста:
- Доброго дня, друзья.
  Это первый и надеюсь, не последний выпуск подкаста "Драконы не дремлют". Здесь я буду рассказывать про свои любимые настольно-ролевые игры, возможно фильмы
  и прочие подобные вещи.
  И сегодня мы начнем с того, с чего начинается любая игра жанра рпг - с создания персонажа.
  Для примера возьмем самую популярную ролевую игру в мире - "Подземелья и драконы".
- Это не так сложно, как может показаться на первый взгляд.
  Для начала придумайте образ своего персонажа. Это будет хитрый и ловкий полурослик или могучий и покрытый шрамами и татуировками воин? А может вам
  приглянулся персонаж какой-нибудь игры или книги. Что ж, вы вольны создать и его прообраз.
- Придумав образ, выберите расу своего персонажа.
  Будет ли это орк или может быть эльф. А вдруг вам нравятся драконорожденные или дварфы?
  Раса влияет не только на то, как вашего персонажа будут воспринимать в мире игры, но и на характеристики.
- Затем стоит выбрать класс персонажа.
  Подробнее классы мы разберем в следующих выпусках, но классы определяют род занятий персонажа, то, чем он знаменит или чем выделяется в мире игры.
- Есть шесть характеристик, а именно сила, ловкость, телосложение, интеллект, мудрость и харизма.
  Это основные параметры, определяющие что за персонажа вы создаете. 
- Откуда берутся значения характеристик?
  Вы генерируете шесть значений характеристик случайно. Бросьте четыре 6-гранных кости и запишите сумму трёх наибольших результатов на листке
для заметок. Проделайте это ещё пять раз, чтобы у вас получилось 6 чисел. Если вы хотите сэкономить время или вам не нравится идея случайного опре-
деления значений характеристик, вы можете использовать следующие числа: 15, 14, 13, 12, 10, 8  
- Затем вы можете выбрать снаряжение своего персонажа. Оно позволит глубже отыгрывать персонажа и наносить, например больше урона. Если вы варвар и решили
  взять на вооружение двуручный меч, это будет явно эффективнее, чем сражаться кулаками.
- На этом начальная подготовка персонажа завершена. Можно играть. Но в следующем выпуске мы разберем дополнительные возможности при создании персонажа.
  А теперь вперед, к приключениям!.

* Выпуск 2
Всем привет. Это второй выпуск "Драконов, которые не дремлют". В прошлый раз мы в очень общих чертах разобрали создание персонажа.
Теперь же, будем делать это на примерах и по шагам, так чтобы даже гоблин из дремучего леса мог разобраться.
Для начала выберем образ нашего персонажа. Мне вот нравятся эльфы, изящные и ловкие. А также, нравятся следопыты.
Интересные они. Выберем картинку, например на pinterest.com.
Итак. Теперь мы примерно знаем как выглядит наш персонаж. Можем придумать ему имя и фамилию. А также возраст.
Я назову своего Гилтас, а фамилию по принципу индейцев придумаю. Ну, пусть будет Меткий. Гилтас Меткий.
Теперь в книге игрока смотрим бонусы и показатели расы и класса.
У эльфа-следопыта бонус +2 к ловкости. 12 страница книги игрока.
Теперь мы переходим к костям хитов. Или говоря проще, показателю жизни персонажа.
Кости хитов зависят от вашего класса. На первом уровне у вас одна такая кость.
Следопыт и его кость 1к10. Стало быть вам нужно бросить один десятигранный кубик, если нет под рукой - не стоит беспокоиться.
В интернете полно сайтов, позволяющих бросать кости. Парочку ссылок оставлю в описании.
К значению, которое в итоге получилось, нужно будет впоследствии прибавить модификатор телосложения.
Его мы вычислим в следующем выпуске.
Итак, пишите в комментариях каких персонажей вы придумали и какие вопросы у вас возникли на этом этапе.
А теперь, всем удачи!

* Выпуск 3 - (А на деле 0)
Всем привет. С вами подкаст "Драконы не дремлют".
Это выпуск третий, но по факту с него стоило начать.
-Что вообще такое эти ваши настольно-ролевые игры и что для них нужно?
На эти вопросы мы сегодня и ответим.
-Настольно-ролевые игры выросли из варгеймов - игр с солдатиками.
И однажды получились НРИ, фактически отделившись от игр настольных.
Получилось нечто иное, где вы командуете лишь одним героем в мире,
который вам представляет ведущий. Вместе с друзьями вы совместно пишете
историю этого мира так, как вам нравится.
Для игры существуют правила. Например, для днд это классическое троекнижие.
-Книга игрока, которая рассказывает о том, как создать персонажа и каким интересным он может стать.
-Книга мастера, позволяющая ведущему создавать приключения и регулировать игру в зависимости от того,
сколько игроков с ним играет.
-И наконец, бестиарий, сборник самых разнообразных монстров и существ, которых мастер может
добавить в игру.
Но вам необязательно читать талмуды правил. Мастер знает или знает где найти большинство правил,
и вполне может помочь разобраться с нюансами и подробностями.
-ДнД не зря называют игрой ручки и бумаги. Pan and paper, так сказать.
Для игры вам потребуется лист персонажа, ручка и фантазия.
В лист персонажа вы внесете всю необходимую информацию, будь то предыстория героя, его имя,
снаряжение, а также пункты здоровья и прочие характеристики. Играя, вы постепенно будете
менять некоторые пункты, добавляя опыт, снаряжение и заклинания.
Листы персонажа, куда вы заносите характеристики и прочие данные, можно бесплатно скачать на
официальном сайте игры.
Распечатайте их или перечертите в блокнот, заполните и всё, вы готовы играть.
-В этом подкасте мы будем разбирать пошагово нюансы и фишки для игры в НРИ.
Подписывайтесь на нас в телеграмме, яндекс.музыке и гугл подкастах.
-И пусть на ваших кубах всегда выпадают двадцатки!
* Выпуск 3
* Выпуск 4
** Класс доспеха, инициатива и скорость.
Всем привет.
В эфире подкаст "Драконы не дремлют"
Сегодня мы поговорим про класс доспеха, инициативу и скорость, поскольку эти атрибуты находятся
на листе персонажа рядышком.
*** Класс доспеха
Аббревиатуры: КД, КЗ (класс защиты), КБ (класс брони)
Ваш Класс Доспеха определяет, насколько хорошо ваш персонаж избегает ранений в бою.
На КД влияет надетый доспех, удерживаемый щит и модификатор Ловкости.
Однако не все персонажи носят доспехи и щиты.
Без доспеха и щита КД вашего персонажа равен 10 + модификатор Ловкости.
Если ваш персонаж одет в доспех, снаряжён щитом или и тем и другим,
рассчитайте ваш КД и запишите его в лист персонажа.
Ваш персонаж должен владеть доспехами и щитом, чтобы использовать их эффективно.
Владение доспехами и щитом определяется классом.
Некоторые заклинания и классовые умения позволяют вам рассчитывать ваш КД другим способом.
Как это работает?
Когда ваш персонаж вступает в бой, и вот-вот получит удар мечом от противника, то ваш класс доспеха
будет служить защитой. И если враг, кинув кубик на попадание, выкинул значение меньше вашего класса брони, то
это засчитывается как промах. То есть, имея кд 15, любые броски на попадание меньше этого значения не нанесут вам никакого вреда.
*** Инициатива
Как скоро вы действуете в бою.
В начале каждого сражения вы совершаете проверку инициативы, совершая проверку Ловкости.
Инициатива определяет порядок ходов существ в сражении.
Чем выше получится ваша инициатива. тем раньше вы сможете совершить действия в бою.
*** Скорость
Скорость персонажа имеет значение также в бою, поскольку определяет какое расстояние он может преодолеть за один ход.
Выбрав расу, в её описании вы отдельным пунктом увидите и скорость, свойственную данному виду.
Например, при скорости в 30 футов, вы можете преодолеть такое расстояние, если например, вам нужно сначала настигнуть неприятеля.

Спасибо за прослушивание данного выпуска, подписывайтесь на нас в телеграмме и слушайте на всех доступных платформах.
Ссылки в описании)
И пусть вам всегда выпадают двадцатки!
* Выпуск 6
** 

