#+TITLE: Мои заметки об орг моде
#+AUTHOR: Kartashov_VA
#+TAGS: 
* Наблюдения и полезные функции: 
** Если зажать Shift и стрелки вверх или вниз - можно менять приоритет задачи очень быстро
* Headings
** Welcome to Org mode

     Lines starting with * are headings.
     These lines without are notes.
*** Sub-heading

     Two stars mark a 2nd-level subheading (h2).
* Lists
To buy:
1. Milk
2. Eggs
   - Organic
3. Cheese
   + Parmesan
   + Mozarella 
* Inline styles
*bold* (**)
/italic/ (/)
_underline_  (__)
=code= (=)
~verbatim~ (~)
+strike-through+ (+)
* To do
** TODO buy airplane
 Cycle by using S-LEFT / S-RIGHT. List all TODO’s via C-c C-v.
* Basic shortcuts
(Un) fold	TAB / S-TAB
Move up	M-UP / M-DOWN
New headline	M-RET
Cycle workflow	S-LEFT / S-RIGHT
Cycle priority	S-UP / S-DOWN
* Timer
Start timer	C-c C-x 0
Stop timer	C-c C-x _
Pause timer	C-c C-x ,
Start countdown	C-c C-x ;
You can use this for Pomodoro!
* Agenda
Agenda menu	C-c a
Add document	C-c [
Remove document	C-c ]
Add date	C-c .
Add time & date	C-u C-c .
Start by adding the current file to the agenda (C-c [), then use the agenda menu to navigate.
* Export
Export menu	C-c C-e
Lets you export the document as Markdown, HTML, and others.
